### ISSUE TITLE
Tasks are run multiple times for the same effective_shift

### ISSUE THREAD

**Issue by mafrahm** [uhh-cms/columnflow#146]
Starting a task with multiple shifts that result in the same `effective_shift` runs the task for each shift, even though each task results in the same output.

Example command:
`law run cf.ReduceEventsWrapper --version v1 --datasets tt_sl_powheg --shifts nominal,pdf_up --configs config_2017_limited --workers 4`
(this will start the `cf.ReduceEvents` for nominal and pdf_up, even though they produce the same output)

**Comment by riga** [comment]
I can confirm...
The fix affects most certainly just a single line, but we might want to tune the systematic shift resolution while we're debugging this. I think there are two options:

- either we skip tasks manually in the wrapper task combinatorics that are not subject to a different effective_shift, or
- we tweak the shift / effective_shift handling so that both tasks (in your example) are logically the same since they don't differ.
