### ISSUE TITLE
Handle sandbox name collisions

### ISSUE THREAD

**Issue by riga** [uhh-cms/columnflow#211]
Right now, sandboxes (venv, cmssw) are installed in directories that only contain the name of the respective sandbox. However, when there are identically named sandboxes, for instance defined once in CF and once in the analysis, they currently use the same install directory, which we probably do not want.

**Comment by dsavoiu** [comment]
Name collisions are definitely something we should fix, so +1 for PR #212 :)

That being said, it's unclear if having user sandboxes with the same name as default CF sandboxes should be explicitly supported/encouraged, since this seems to me prone to create confusion. Of course it can happen during development or if a sandbox is added to CF with the same name as an existing user sandbox, but other than that, is there a valid use-case for analysis redefining their own, say, `venv_columnar` sandbox? Maybe we should make a note to address this in the documentation when discussing sandboxes.

**Comment by riga** [comment]
I also don't think this would happen too often. As an example, in our analysis we happen to have a cmssw sandbox that we would also like to name "cmssw_default". Since this is also the name of a sandbox in cf, I ran into this in a real scenario :)

And indeed, we should mention this in the sandboxing documentation :+1: (noted)
