### ISSUE TITLE
Move cmssw env in plotting task to venv

### ISSUE THREAD

**Issue by riga** [uhh-cms/columnflow#26]

**Comment by bonanomi** [comment]
There's something I am failing to understand.

`CMSSW_12_2_3` should come with `python3.6`, however when the `sandbox = "bash::$AP_BASE/sandboxes/cmssw_default.sh"` sandbox is used in the plotting task, the `python` version used is `python3.9`.
@riga @mafrahm could you help me understanding where this source of python 3.9 is happening ?

Setting up a proper `venv` akin to `venv_columnar` is trivial, but the problem is that in doing so `python3.6.8` is sourced and `[matplotlib.ax.](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.stairs.html)` is only available from `python3.7`, therefore the venv approach isn't working because `stairs` is not available in `matplotlib v3.4.*`.

I tried to look for `python3.9` in `/cvmfs/cms.cern.ch/slc7_amd64_gcc900` but seems not to be there, so not sure where this version can be taken from in setting up a venv for this.

**Comment by riga** [comment]
As you might have already heard from @kramerto , this is possible, but we need to make a few small changes to generalize the venv setup. Let's focus on this in the [hackathon](https://github.com/orgs/uhh-cms/projects/1) later today ;)

**Comment by riga** [comment]
@bonanomi Correct me if I'm wrong, but I think we can close this for now, right?

I think the issue was that we are a bit stuck with Python 3.6 which is the default Python 3 version on CC7/8 machines :/.
To be consistent with the environment present at the usual machines (NAF, lxplus, WLCG nodes, etc), we should stick with the Python 3.6 constraint, **or** we find a way to easily ship our own Python with our jobs. However, this could lead to weird interferences with the LCG software stack (currently at `/cvmfs/grid.cern.ch/centos7-ui-160522/etc/profile.d/setup-c7-ui-python3-example.sh`) which provides us with GFAL bindings to interact with remote files.

IMHO, we should wait until the LCG team provides their stack for a newer Python version and then revisit this issue.
